title: PEPSys @ PLUS
author: Privacy Engineering and Policy-Aligned Systems Group
theme: Minima
languages: ["en", "de"]
description: The Privacy Engineering and Policy-Aligned Systems Group at Paris Lodron University Salzburg (PEPSys @ PLUS), led by Prof. Frank Pallas, bridges the gap between the design and engineering of cutting-edge enterprise-grade systems on the one and the legal and policy-related aspects shaping such systems on the other hand.
header_pages:
- README.md
- team.md
- research.md
- projects.md
- publications.md
